version: '3.8'

services:
  postgres:
    container_name: abrace_cdc_api
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=abrace